# transistor.appveyor.yml
# ~~~~~~~~~~~~
# Configuration file for testing Transistor with appveyor CI
#
# :copyright: Copyright (C) 2018 by BOM Quote Limited
# :license: The MIT License, see LICENSE for more details.
# ~~~~~~~~~~~~

# scripts that are called at very beginning, before repo cloning.
init:
  - git config --global core.autocrlf input
  - SET PATH=C:\Program Files\PostgreSQL\12\bin\;C:\Miniconda38-x64\Scripts;C:\Program Files\Docker\Docker\resources\bin;D:\host\transistor\tests\;%PATH%;%PYTHONPATH%;%PYTHONPATH%\Scripts%PATH%,
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# clone directory
clone_folder: D:\host\transistor

# Build worker image (VM template)
image: Windows Server 2019

# setting up etc\hosts file
hosts:
  local: 127.0.0.1
  localhost: 127.0.0.1

# environment variables
environment:
  PYTHONUNBUFFERED: 1
  PYTHON_EXE: 'C:\Miniconda38-x64\envs\transistor\python.exe'
  PYTHON_LIB: 'C:\Miniconda38-x64\envs\transistor\Lib\site-packages'
  BASE_PATH: 'D:host\transistor\transistor\'
  APP_DIR: 'D:\host\transistor\transistor'
  PROJECT_ROOT: 'D:\host\transistor'
  TEMP: 'C:\temp\'
  SPLASH_USERNAME: 'user'
  SPLASH_PASSWORD: 'userpass'

  matrix:
  - TARGET_ARCH: x64
    CONDA_PY: 3.8
    PY_CONDITION: python >=3.8
    CONDA_INSTALL_LOCN: C:\\Miniconda38-x64
    db: postgresql121

  global:
      # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
      # /E:ON and /V:ON options are not enabled in the batch script interpreter
      # See: http://stackoverflow.com/a/13751649/163740
      # CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
      PGUSER: postgres
      PGPASSWORD: Password12!

# cache:
    #- C:\ProgramData\chocolatey\lib -> appveyor.yml
    #- C:\Users\appveyor\pip\wheels -> appveyor.yml

# enable service required for build/tests
services:
  - postgresql121     # start PostgreSQL 12 service
  - docker

install:
    # If there is a newer build queued for the same PR, cancel this one.
    # The AppVeyor 'rollout builds' option is supposed to serve the same
    # purpose but it is problematic because it tends to cancel builds pushed
    # directly to master instead of just PR builds (or the converse).
    # credits: JuliaLang developers.
    - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }

    # Use the pre-installed Miniconda3 for the desired arch
    - ps: if($env:TARGET_ARCH -eq 'x86')
            {$root = "C:\Miniconda38"}
          else
            {$root = "C:\Miniconda38-x64"}
          $env:path="$root;$root\Scripts;$root\Library\bin;$root\Library\usr\bin;$($env:path)"
    - cmd: mkdir c:\temp
    # deal with switching docker to linux containers
    # see: https://ci.appveyor.com/project/appveyor-tests/docker-ce/build/1.0.29
    - ps: gcim Win32_Processor | % { "$($_.NumberOfCores) cores" }
    - ps: gcim Win32_OperatingSystem | % { "$([int]($_.TotalVisibleMemorySize/1mb)) Gb" }
    - cmd: docker-switch-linux
    # start aquarium
    - ps: D:\host\transistor\appveyor\docker-compose-up.ps1
    # start postgreSQL
    - ps: D:\host\transistor\appveyor\install_postgresql_12.ps1
    # - ps: net start postgresql-x64-12
    # download and install redis for windows
    - cmd: cd c:\ && mkdir c:\redis-3.2.100
    - ps: D:\host\transistor\appveyor\redis.ps1
    # install erlang
    # - ps: D:\host\transistor\appveyor\install_erlang.ps1
    # install rabbitmq
    - ps: D:\host\transistor\appveyor\rabbitmq.ps1
    # Load the conda root environment, configure and install packages
    - cmd: conda config --set show_channel_urls true
    - cmd: conda config --set always_yes yes --set changeps1 no
    - cmd: conda update --yes --quiet conda
    - cmd: conda env create --file=D:\host\transistor\environment.yml
    - cmd: activate transistor
    - cmd: set PYTHONUNBUFFERED=1
    - cmd: set PYTHONPATH=C:\Miniconda38-x64\envs\transistor;
    # upgrade pip
    - cmd: python -m pip install --upgrade pip
    # install packages from pip
    - cmd: python -m pip install -r D:\host\transistor\requirements\dev.txt
    # check the rabbit connection
    - cmd: python D:\host\transistor\appveyor\check_rabbitmq_connection.py
    # - cmd: netstat -a

# Skip .NET project specific build phase.
build: off

test_script:
    - cmd: python -m pytest D:\host\transistor\tests -rfs --tb=short --disable-warnings


# after_test:
    # Upload coverage reports
#    - 'codecov -f "%HOMEPATH%\coverage.xml"'
