name: python37
channels:
- trelau
- peterjc123
- conda-forge
- alubbock
- anaconda
- dlr-sc
- defaults
dependencies:
- python=3.7.2
- pandas=0.24.0
- scipy=1.2.0
- scikit-learn=0.20.2
- matplotlib=3.0.2
- cython=0.29.4
- graphviz=2.41
- pygraphviz=1.5
- freetype=2.9.1
- pywin32=224
- shapely=1.6.4

prefix: C:\Miniconda37-x64\envs\pythonocc

# updated 2/3/2019